env:
    browser: false
    node: true
    es6: true
globals:
    process: true
parserOptions:
    ecmaVersion: 7
plugins:
    - babel
rules:
  comma-dangle:
    - 1
    - always-multiline
  no-cond-assign:
    - 2
    - always
  no-console: 2
  no-constant-condition: 2
  no-control-regex: 0
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-empty: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens: 2
  no-extra-semi: 1
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-regex-spaces: 1
  no-sparse-arrays: 2
  no-unreachable: 2
  use-isnan: 2
  valid-jsdoc: 1
  valid-typeof: 2
  accessor-pairs:
    - 2
    -
      getWithoutSet: true
  block-scoped-var: 2
  complexity:
    - 2
    - 5
  consistent-return: 2
  curly: 2
  default-case: 2
  dot-location:
    - 1
    - 'property'
  dot-notation:
    - 2
    - allowPattern: "^[a-z]+[A-Za-z]+$"
  eqeqeq:
    - 2
    - smart
  guard-for-in:
    - 2
  no-alert: 2
  no-caller: 2
  no-case-declarations: 2
  no-div-regex: 2
  no-else-return: 1
  
  no-empty-pattern: 2
  
  no-eq-null: 2
  
  no-eval: 2
  
  no-extend-native: 2
  
  no-fallthrough: 2
  
  no-floating-decimal: 2
  
  no-implied-eval: 2
  
  no-lone-blocks: 1
  
  no-loop-func: 2
  
  no-magic-number: 0
  
  no-multi-spaces: 1
  
  no-native-reassign: 2
  
  no-new-func: 2
  
  no-param-reassign:
    - 2
    - props: true
  
  no-proto: 2
  
  no-redeclare: 2
  
  no-script-url: 2
  
  no-self-compare: 2
  
  
  no-sequences: 2
  
  no-unused-expressions: 1
  
  no-throw-literal: 1
  
  no-void: 2
  no-warning-comments:
    - 2
    - terms:
      - hack
      - fix
  
  no-with: 2
  
  vars-on-top: 2
  
  yoda: 2
  
  init-declarations:
    - 2
    - always
  
  no-catch-shadow: 2
  
  no-delete-var: 2
  
  no-shadow-restricted-names: 2
  
  
  no-undef: 2
  
  no-undef-init: 2
  
  no-unused-vars: 1
  
  no-use-before-define: 2
  callback-return: 1
  global-require: 2
  handle-callback-err:
    - 2
    - "^(err|error)$"
  no-mixed-requires:
    - 1
    - grouping: true
  no-new-require: 2
  no-path-concat: 2
  array-bracket-spacing:
    - 1
    - never
  block-spacing:
    - 1
    - always
  brace-style:
    - 1
  camelcase:
    - 2
  comma-spacing: 1
  comma-style:
    - 2
    - last
  computed-property-spacing:
    - 2
    - never
  consistent-this:
    - 2
    - self
  eol-last: 1
  func-style:
    - 1
    - expression
  id-match:
    - 2
    - "^\\$?[A-Za-z_][A-Za-z_0-9]*$"
    - properties: true
  indent:
    - 2
    - 4
  key-spacing:
    - 1
  max-depth:
    - 2
    - 5
  max-len:
    - 2
    - 100
    - 4
  max-nested-callbacks:
    - 2
    - 4
  new-cap: 2
  new-parens: 2
  no-array-constructor: 2
  no-lonely-if: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
   - 1
   -
     max: 3
     maxEOF: 1
  no-negated-condition: 2
  no-nested-ternary: 2
  no-spaced-func: 2
  no-trailing-spaces: 1
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  object-curly-spacing:
    - 2
    - never
  quotes:
    - 2
    - single
    - avoid-escape
  semi-spacing: 1
  semi:
    - 1
    - always
  space-before-blocks:
    - 1
    - always
  space-before-function-paren:
    - 1
    - always
  no-labels: 2
  keyword-spacing: [2, {"after": true, "before": true}]
  space-in-parens:
    - 1
    - never
  space-infix-ops: 1
  space-unary-ops: 1
  arrow-body-style:
    - 2
    - as-needed
  arrow-parens:
    - 2
    - as-needed
  arrow-spacing:
    - 1
  constructor-super: 2
  generator-star-spacing:
    - 1
  no-arrow-condition: 0
  no-class-assign: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-this-before-super: 2
  prefer-template: 1
  prefer-const: 2
  no-var: 2
  require-yield: 0
